# Generated by Django 5.0.6 on 2024-07-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_province_record_state_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Id',
        ),
    ]
