# Generated by Django 5.0.7 on 2024-07-11 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_record_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.AddField(
            model_name='record',
            name='province',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
    ]
